# Generated by Django 3.1.2 on 2020-10-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.CharField(help_text='Latitude of Squirrel', max_length=100)),
                ('Longitude', models.CharField(help_text='Longitude of Squirrel', max_length=100)),
                ('Unique_Squirrel_ID', models.CharField(help_text='ID of Squirrel', max_length=100)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift of Squirrel', max_length=15)),
                ('Date', models.CharField(blank=True, help_text='Date of finding Squirrel', max_length=20)),
                ('Age', models.CharField(blank=True, help_text='Age of Squirrel', max_length=15)),
            ],
        ),
    ]
