# Generated by Django 3.1.2 on 2020-10-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(help_text='Age of Squirrel', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateTimeField(help_text='Date of finding Squirrel (sighting)'),
        ),
    ]
