# Generated by Django 3.1.2 on 2020-10-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrels', '0002_auto_20201015_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', '?')], help_text='Age of Squirrel', max_length=15),
        ),
    ]
