# Generated by Django 3.1.2 on 2020-10-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrels', '0005_auto_20201020_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(help_text='yyyy-mm-dd'),
        ),
    ]
